package com.daffamuhtar.taskcm.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val DarkColorScheme = darkColorScheme(
    primary = GreenPrimaryDark,
    secondary = GreenSecondaryDark,
    tertiary = GreenTertiaryDark,
    onPrimary = OnGreenDark,
    primaryContainer = GreenContainerDark,
    onPrimaryContainer = OnGreenContainerDark,
    onSecondary = OnGreenSecondaryDark,
    secondaryContainer = GreenSecondaryContainerDark,
    onSecondaryContainer = OnGreenSecondaryContainerDark,
    onTertiary = OnGreenTertiaryDark,
    onTertiaryContainer = OnGreenTertiaryContainerDark,
    tertiaryContainer = GreenTertiaryContainerDark,
    background = BackgroundDark,
    onBackground = OnBackgroundDark,
    surface = SurfaceDark,
    onSurface = OnSurfaceDark,
    surfaceVariant = SurfaceVariantDark,
    onSurfaceVariant = OnSurfaceVariantDark,
    error = ErrorDark,
    onError = OnErrorDark,
    errorContainer = ErrorContainerDark,
    onErrorContainer = OnErrorContainerDark,
    outline = OutlineDark,
)

val LightColorScheme = lightColorScheme(
    primary = color_yellow,
    secondary = color_blue,
    tertiary = color_yellowdark,
    onPrimary = color_black,
    primaryContainer = color_yellowsoft,
    onPrimaryContainer = color_yellowdark,
    onSecondary = color_white,
    secondaryContainer = color_bluesoft,
    onSecondaryContainer = color_blue,
    onTertiary = OnGreenTertiaryLight,
    onTertiaryContainer = OnGreenTertiaryContainerLight,
    tertiaryContainer = GreenTertiaryContainerLight,
    background = BackgroundLight,
    onBackground = OnBackgroundLight,
    surface = SurfaceLight,
    onSurface = OnSurfaceLight,
    surfaceVariant = SurfaceVariantLight,
    onSurfaceVariant = OnSurfaceVariantLight,
    error = ErrorLight,
    onError = OnErrorLight,
    errorContainer = ErrorContainerLight,
    onErrorContainer = OnErrorContainerLight,
    outline = OutlineLight,

//    primary = GreenPrimaryLight,
//    secondary = GreenSecondaryLight,
//    tertiary = GreenTertiaryLight,
//    onPrimary = OnGreenLight,
//    primaryContainer = GreenContainerLight,
//    onPrimaryContainer = OnGreenContainerLight,
//    onSecondary = OnGreenSecondaryLight,
//    secondaryContainer = GreenSecondaryContainerLight,
//    onSecondaryContainer = OnGreenSecondaryContainerLight,
//    onTertiary = OnGreenTertiaryLight,
//    onTertiaryContainer = OnGreenTertiaryContainerLight,
//    tertiaryContainer = GreenTertiaryContainerLight,
//    background = BackgroundLight,
//    onBackground = OnBackgroundLight,
//    surface = SurfaceLight,
//    onSurface = OnSurfaceLight,
//    surfaceVariant = SurfaceVariantLight,
//    onSurfaceVariant = OnSurfaceVariantLight,
//    error = ErrorLight,
//    onError = OnErrorLight,
//    errorContainer = ErrorContainerLight,
//    onErrorContainer = OnErrorContainerLight,
//    outline = OutlineLight,
)